#!/bin/bash

apt install pwgen > /dev/null 2>&1

if [ ! -d "/etc/freeradius/3.0/group" ]
then
	mkdir /etc/freeradius/3.0/group
fi

echo "Entrez le nom des utilisateurs"
read nom

carac=0

while [ $carac -lt 5 ]
do
	echo "Nombre de caracteres pour le mot de passe: (minimum 5 lettres)"
	read carac
done

echo "Entrez le nombre d'utilisateurs que vous souhaitez:"
read nbr

for id in `seq $nbr`
do
	mdp=`pwgen $carac 1`
	echo "$nom$id;Cleartext-Password;:=;$mdp" >> ../group/$nom.csv
done

echo "Utilisateurs créer dans /etc/freeradius/3.0/group/$nom"

